### ISSUE TITLE
Range component is missing from search results

### ISSUE THREAD

**Issue by abitrolly** [observablehq/documentation#128]
The guide asks for Range component, but it is absent from the search menu.

![image](https://github.com/observablehq/documentation/assets/8781107/115b776b-061b-4243-ba53-d9a5456dc0ed)

**Comment by mootari** [comment]
Thanks for the report! We already have the issue logged as https://github.com/observablehq/feedback/issues/606 so I'm going to close this one as duplicate. 🙏🏻

**Comment by abitrolly** [comment]
@mootari it may worth to pin the feedback repo here https://github.com/observablehq

**Comment by abitrolly** [comment]
@tophtucker good to know. Thanks.

Are you going to pin the feedback repo too, to make it discoverable?
