### ISSUE TITLE
Text gets cropped instead of wrapping in FileAttachment API table

### ISSUE THREAD

**Issue by pettiross** [observablehq/documentation#130]
In [the table listing the FileAttachment API methods](https://observablehq.com/documentation/data/files/file-attachments#fileattachment-api), some of the descriptions in the second column are cropped. This text should be wrapped instead.

<img width="723" alt="image" src="https://github.com/observablehq/documentation/assets/3514378/156a9eb2-4891-4fe8-a149-3db7c837b2db">

**Comment by pstuffa** [comment]
There is actually an x-scroll at the bottom, but agreed it would be better if they wrapped.

**Comment by eagereyes** [comment]
[PR here](https://github.com/observablehq/documentation/pull/139)
