### ISSUE TITLE
Inputs menu on left has dead link for the Form entry

### ISSUE THREAD

**Issue by jwoLondon** [observablehq/documentation#133]
The menu entry for `Form` to the left of the Inputs page has a dead link to `#and-more` but I think should be to [https://observablehq.com/@observablehq/input-form](https://observablehq.com/@observablehq/input-form) (unless there are plans to update form documentation on the same page).

**Comment by eagereyes** [comment]
Hi Jo, thanks so much for filing this issue! I'm adding a simple fix for now, we'll be revisiting the structure of the sidebar soon as well.
