### ISSUE TITLE
Clicking PricingBadge component takes you to documentation home, not pricing page

### ISSUE THREAD

**Issue by tophtucker** [observablehq/documentation#134]
This link goes to the wrong place:

<img width="177" alt="image" src="https://github.com/observablehq/documentation/assets/841829/4f5a106c-520c-463f-89ba-190327120e12">

Weirdly, the link _looks like_ it’s going to https://observablehq.com/pricing:

<img width="469" alt="image" src="https://github.com/observablehq/documentation/assets/841829/c2859722-a54e-4d7b-b29e-58f7ecb53fff">

But if you actually click it, it goes to the documentation homepage.

It works fine locally! It’s only in production that it breaks.

Ideally, the “Pro” also wouldn’t have an underline.

cc @eagereyes @observable-hanna

**Comment by eagereyes** [comment]
[PR here](https://github.com/observablehq/documentation/pull/135). Can't test it locally, but I hope this will fix it.

**Comment by eagereyes** [comment]
Looks like this fixed it, even at the cost of more tabs when people click the link…
