### ISSUE TITLE
Cells ⟩ JavaScript link is broken

### ISSUE THREAD

**Issue by tophtucker** [observablehq/documentation#147]
The “JavaScript” heading under which Observable JavaScript and Require are nested 404s:

https://observablehq.com/documentation/cells/javascript

<img width="235" alt="image" src="https://github.com/observablehq/documentation/assets/841829/ae5d9821-40a1-4285-9aa8-5e7fc9d26cc0">

**Comment by tophtucker** [comment]
oh snap now i can't reproduce. what was i doing, where was i coming from? hmm… if nobody else can reproduce we can close, sorry!

**Comment by pstuffa** [comment]
I can't seem to reproduce, but we'll keep an eye on it!
